### ISSUE TITLE
Misc

### ISSUE THREAD

**Issue by juliohq** [zhaoshenzhai/MathWiki#1]
A very interesting repository with useful knowledge for other students/obsidian lovers like me. May I ask you which Arch Linux DE/themes were you using in the screenshots in your README? That's really beautiful.

**Comment by zhaoshenzhai** [comment]
Thanks! Im glad you found it helpful.

The details of my linux setup should not affect how my obsidian vault looks, but rather how it functions (as my vault is very script-dependent). As for how it looks, here are some details.

- The only visible parts in my screenshots that is not part of obsidian, but rather part of my linux setup, is the top bar (with all the icons and info), which I used xmobar for. I didn't use any themes since I wanted my linux to have my own look and feel, but all the configurations can be found in my [dotfiles](https://github.com/zhaoshenzhai/dotfiles) repository.
- I use the minimal theme with the style-settings plugin (all settings can be found [here](https://github.com/zhaoshenzhai/MathWiki/tree/master/.obsidian)). I also have some custom `CSS`, which better ingerates the theme with how my linux system looks and feels.
- In the screenshots, you might notice that the links support mathjax. This _can_ be done in obsidian without plugins, but managing them is hard, so I made a plugin, [MathLinks](https://github.com/zhaoshenzhai/obsidian-mathlinks), that handles rendering/managing mathjax in links. If you use obsidian for math, you might find this useful too!
- The figures in my screenshots were written in LaTeX + TikZ. My workflow is documented in the `README`.

Currently the only way to experiment with my vault is to clone this repository and use it locally, but is not ideal. I hope to one day host this online somehow, but I've yet to have time to set things up.
