### ISSUE TITLE
main.sh not working?

### ISSUE THREAD

**Issue by RasmusRaschke** [zhaoshenzhai/mathwiki#8]
Hello,

I would like to use your (really beautiful) mathwiki to create my own wiki in a similar fashion, but I ran into two problems (which I think are related):

1. Obsidian doesn't render some parts of the note, here an example:

cayleys_theorem
title
Cayley’s Theorem
date
2024-06-20T19:25:15-04:00
references
Alu09
tags
Group_Theory/Later
Motivation & Statement
Whenever one encounters a type of mathematical object, one should ask if there is an associated ‘representation theorem’. Such a theorem for {{< link file="group" display="groups" type="references" >}} is as follows.

{{< env type="theorem" name="Cayley" >}}

Every group  is a {{< link file="subgroup" display="subgroup" type="references" >}} of a symmetry group.

{{< /env >}}

{{< env type="proof" >}}

We show that the left-multiplication {{< link file="group_action" display="action" type="references" >}}  is faithful, for then . Indeed, if , then we have  for all . That is, we have , so  as desired.

{{< /env >}}

Cayley Graph
We can refine this result if  is finitely-generated.

{{< env type="proposition" >}}

Every finitely-generated group is a subgroup of the symmetries of a connected locally-finite (directed) graph.

{{< /env >}}

{{< env type="proof" >}}

{{< /env >}}

{{< link file="yoneda_lemma" display="The Yoneda Lemma" type="generalizations" >}}

2. When I try to run main.sh, I get the following error message:
.scripts/main.sh 
.scripts/main.sh: line 4: /.scripts/stats.sh: No such file or directory
.scripts/main.sh: line 5: /.scripts/stats.sh: No such file or directory

Actions:
    (1): Git
    (2): Search
    (3): Restore
    (4): Ghost links
    (5): Update images
    (6): Publish notes

Select: [1|(1-6)] 4
.scripts/main.sh: line 31: cd: /Notes: No such file or directory
.scripts/main.sh: line 37: /.scripts/ghostLinks.sh: No such file or directory

DONE

Press [Y] to return, exiting otherwise... 

Do you maybe know how to fix this?

Thank you very much in advance!

**Comment by zhaoshenzhai** [comment]
Hi! Thanks for opening an issue.

1. I've completely rewritten my notes without Obsidian, using slightly different syntax, so that it doesn't render well in Obsidian anymore.
2. `main.sh` is a completely personalized script, written so that I can control my notes through the command line. It doesn't add anything to the existing notes, other than convenience. So I haven't written it so that it could be run on any device.

I plan on translating my existing system into an Obsidian vault, so that while I update notes on my current system, the vault gets updated automatically in parallel. This way, people can access the content both [online](http://localhost:1313/mathwiki/group_action/) and, if they wish, clone it to view the vault locally.

**Comment by RasmusRaschke** [comment]
Hi! Thank you for replying so fast. The earlier version of this repo is more than enough for my purpose. But I have to say that your new online content looks absolutely great!
